name: app_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  easy_padding: ^0.1.7
  flutter:
    sdk: flutter
  flutter_gen: ^5.7.0
  iconly: ^1.0.1
  sizer: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
          weight: 700

flutter_gen:
  output: lib/src/generated/